### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by NavinShrinivas** [acmpesuecc/SimpleGrep#1]
## Preface 

Any refactoring is accepted! Following the cargo clippy is appreciated :))

## Details 

- Max block time : 30 mins
- open access time : None [This is exception]
- bounty : 15-50  [Depending on amount of refactor]

**Comment by shrutidewan** [comment]
can I work on this?

**Comment by gybrish** [comment]
Any chance of getting a review on the PR? :)

**Comment by NavinShrinivas** [comment]
Hey yeah sure, this looks good! The delay was because I wasn't sure if it was part of an internal event.
